const quotes = [
  { text: "A room without books is like a body without a soul.", author: "Cicero" },
  { text: "I have always imagined that Paradise will be a kind of library.", author: "Jorge Luis Borges" },
  { text: "Good friends, good books, and a sleepy conscience: this is the ideal life.", author: "Mark Twain" },
  { text: "Reading is essential for those who seek to rise above the ordinary.", author: "Jim Rohn" },
  { text: "There is no friend as loyal as a book.", author: "Ernest Hemingway" },
  { text: "Today a reader, tomorrow a leader.", author: "Margaret Fuller" },
  { text: "So many books, so little time.", author: "Frank Zappa" },
  { text: "A book is a dream that you hold in your hand.", author: "Neil Gaiman" },
  { text: "Books are a uniquely portable magic.", author: "Stephen King" },
  { text: "Whenever you read a good book, somewhere in the world a door opens to allow in more light.", author: "Vera Nazarian" },
  { text: "We lose ourselves in books, we find ourselves there too.", author: "Anonymous" },
  { text: "Reading gives us someplace to go when we have to stay where we are.", author: "Mason Cooley" },
  { text: "Books are mirrors: you only see in them what you already have inside you.", author: "Carlos Ruiz Zafón" },
  { text: "A book is a device to ignite the imagination.", author: "Alan Bennett" },
  { text: "There is no Frigate like a Book to take us Lands away.", author: "Emily Dickinson" },
  { text: "Reading one book is like eating one potato chip.", author: "Diane Duane" },
  { text: "A book is a garden, an orchard, a storehouse, a party, a counselor, a multitude of counselors.", author: "Charles Baudelaire" },
  { text: "Reading fuels the mind.", author: "Unknown" },
  { text: "The only thing you absolutely have to know is the location of the library.", author: "Albert Einstein" },
  { text: "Words are, in my not-so-humble opinion, our most inexhaustible source of magic.", author: "J.K. Rowling" },
  { text: "Fill your house with stacks of books, in all the crannies and all the nooks.", author: "Dr. Seuss" },
  { text: "Reading is dreaming with open eyes.", author: "Unknown" },
  { text: "Books let us into their souls and lay open to us the secrets of our own.", author: "William Hazlitt" },
  { text: "A great book should leave you with many experiences, and slightly exhausted at the end.", author: "William Styron" },
  { text: "No two persons ever read the same book.", author: "Edmund Wilson" },
];

export default quotes;

